//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualCollege.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disc
    {
        public Disc()
        {
            this.IssueDiscs = new HashSet<IssueDisc>();
        }
    
        public int DiscId { get; set; }
        public string DiscTitle { get; set; }
        public string Artist { get; set; }
        public string Director { get; set; }
        public string Distributor { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public string Language { get; set; }
        public string Subtitle { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public string Duration { get; set; }
        public string Status { get; set; }
        public string ThumbnailPicture { get; set; }
    
        public virtual ICollection<IssueDisc> IssueDiscs { get; set; }
    }
}
