//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualCollege.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ebook
    {
        public Ebook()
        {
            this.IssueEbooks = new HashSet<IssueEbook>();
        }
    
        public int EbookId { get; set; }
        public string EbookTitle { get; set; }
        public string Author { get; set; }
        public string Publisher { get; set; }
        public string Category { get; set; }
        public System.DateTime PublishedYear { get; set; }
        public int TotalPages { get; set; }
        public string ISBN { get; set; }
        public string Description { get; set; }
        public string ThumbnailPicture { get; set; }
        public int AvailableCopies { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<IssueEbook> IssueEbooks { get; set; }
    }
}
