//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualCollege.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssueEbook
    {
        public int IssueEbookId { get; set; }
        public int EbookId { get; set; }
        public int UserId { get; set; }
        public int LibrarianId { get; set; }
        public int NumberOfDays { get; set; }
    
        public virtual Ebook Ebook { get; set; }
        public virtual Librarian Librarian { get; set; }
        public virtual Member Member { get; set; }
    }
}
