//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualCollege.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Librarian
    {
        public Librarian()
        {
            this.IssueBooks = new HashSet<IssueBook>();
            this.IssueDiscs = new HashSet<IssueDisc>();
            this.IssueEbooks = new HashSet<IssueEbook>();
        }
    
        public int LibrarianId { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string CellPhone { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<IssueBook> IssueBooks { get; set; }
        public virtual ICollection<IssueDisc> IssueDiscs { get; set; }
        public virtual ICollection<IssueEbook> IssueEbooks { get; set; }
    }
}
