//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualCollege.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int UserId { get; set; }
        public string PaymentType { get; set; }
        public string CardNumber { get; set; }
        public string NameOnCard { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public int CSV { get; set; }
        public string BillingAddress { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string CellPhone { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
