//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualCollege.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PC
    {
        public PC()
        {
            this.ReservePCs = new HashSet<ReservePC>();
        }
    
        public int PCId { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<ReservePC> ReservePCs { get; set; }
    }
}
