//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualCollege.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservePC
    {
        public int PCId { get; set; }
        public string PCName { get; set; }
        public int UserId { get; set; }
        public string Notes { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual PC PC { get; set; }
    }
}
