//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualCollege.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.ReserveRooms = new HashSet<ReserveRoom>();
        }
    
        public int RoomId { get; set; }
        public int Capacity { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<ReserveRoom> ReserveRooms { get; set; }
    }
}
